services:
  customerapi:
    image: ${DOCKER_REGISTRY-}customerapi
    build:
      context: .
      dockerfile: CustomerAPI/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    ports:
     -   8082:80
    depends_on:
      - sqlserverinstance
  sqlserverinstance:
    image: mcr.microsoft.com/mssql/server 
    hostname: 'sqlserverinstance'
    environment:  
      ACCEPT_EULA: 'Y' 
      SA_PASSWORD: "Vignesh@95"
    volumes:  
      - ./customerapi:/var/opt/mssql/data
    ports:  
      - '1403:1433'  
    expose:  
      - 1433
networks: 
  default: 
    external: 
      name: siemensnetwork